name: Deploy functions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install Amazon Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Install dependencies
        run: |
          cd cdk
          npm install
          npm install -g aws-cdk

      - name: Build Python package
        run: |
          cd Python
          zip -r package.zip .

      - name: Build C# x86 package
        run: dotnet lambda package --framework net8.0 --configuration Release --function-architecture x86_64 --output-package ./package_x86.zip
        working-directory: CSharp

      - name: Build C# ARM package
        run: dotnet lambda package --framework net8.0 --configuration Release --function-architecture arm64 --output-package ./package_arm.zip
        working-directory: CSharp

      - name: CDK Synthesize
        run: cdk synth
        working-directory: cdk

      - name: CDK Deploy
        env:
          CI: true
        run: cdk deploy --require-approval never
        working-directory: cdk
