name: Deploy functions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: |
          cd cdk
          npm install
          npm uninstall path
          npm install --save-dev @types/node @types/jest

      - name: Build Python package
        run: |
          cd Python
          zip -r package.zip .
        working-directory: Python

      - name: Build C# x86 package
        run: dotnet lambda package --framework net8.0 --configuration Release --function-architecture x86_64 --output-package ./package_x86.zip
        working-directory: CSharp

      - name: Build C# ARM package
        run: dotnet lambda package --framework net8.0 --configuration Release --function-architecture arm64 --output-package ./package_arm.zip
        working-directory: CSharp

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Check Node.js types
        run: ls -la node_modules/@types/node
        working-directory: cdk

      - name: Compile TypeScript
        run: npx tsc --noEmit
        working-directory: cdk

      - name: CDK Synthesize
        run: cdk synth
        working-directory: cdk

      - name: CDK Deploy
        env:
          CI: true
        run: cdk deploy --require-approval never
        working-directory: cdk
