name: Deploy functions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd cdk
          npm install
          npm uninstall @types/node
          npm install --save-dev @types/node

      - name: Check Node.js types
        run: ls -la node_modules/@types/node
        working-directory: cdk

      - name: Compile TypeScript
        run: npx tsc --noEmit
        working-directory: cdk

      - name: CDK Synthesize
        run: cdk synth
        working-directory: cdk

      - name: CDK Deploy
        env:
          CI: true
        run: cdk deploy --require-approval never
        working-directory: cdk
